### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by yaapis**
Respect dest path parameter

### CODE REVIEW

**Comment by yaapis** [comment]
Changes approved =)
Can u plz merge this request to master?

**Comment by hyprstack** [comment]
@devfubar this is up to you

**Comment by yaapis** [comment]
Yes, but: Only those with write access to this repository can merge pull requests.
I'm not =)

**Comment by yaapis** [comment]
@hyprstack, @devfubar  guys, is there any chance to get some feedback about the request? =)

**Comment by hyprstack** [comment]
@yaapis I'm sorry dude. I am no longer in charge of this repo. @devfubar is who you need to talk to. Sorry I can't help with this.

**Comment by yaapis** [comment]
cheers :)

**Pull request merged**
